theme: jekyll-theme-cayman
title: Knowledge Engineering for Drug Safety: A Systematic and mapping review
description: Files produced during the systematic and mapping review of the scientific papers published regarding Knowledge Engineering and Drug Safety, for the years between 2006 and 2017.
